### ISSUE TITLE
Metadata for example data?

### ISSUE THREAD

**Issue by dpshepherd** [edward-n-ward/MAI-SIM#1]
I just read through your [preprint](https://arxiv.org/abs/2206.00532), very cool project with really nice results!

We have some efforts on open-source multicolor SIM using a DMD ([paper](https://opg.optica.org/boe/viewmedia.cfm?uri=boe-12-6-3700&html=true), [github](https://github.com/QI2lab/mcSIM), [reconstruction tutorials](https://github.com/QI2lab/I2K2022-SIM)). 

I am curious how well our reconstruction approaches handle your data with non $\frac{2\pi}{3}$ phase shift data. We have simulated this situation before, but not dealt with experimental data from another group. Is there metadata (pixel size, em/ex wavelengths) available for the example data in both `Data` and `ML-SIM-inference-for-AtheiSIM`?

Thanks!
Doug

**Comment by edward-n-ward** [comment]
Hi,
Sorry, the repo definitely still needs a bit of polishing! I'm looking at getting all the readmes etc done in the next few days which will include this information. The pixel size is 86nm for all the data acquired though. Either the Ex/Em or the specific fluorophores used should be in the paper. All the excitation wavelengths are laser lines with very narrow bands (<5nm) centred on 491,561,647. The corresponding emission filters are 500-550/575-614/660-755. For any of the simulated data it's slightly harder as obviously it's all intentionally randomised. Possibly adding this information to the metadata of the generated images is something we can look into. However, the code should be here for you to generate your own images with whichever parameters you like. Let me know how you get on and happy to chat more over email if you would like. Cheers,

Edward
